[INTER-708] Response transparency and webhook validation
fingerprintjs/fingerprintjs-pro-server-api-node-sdk pull request #104
Opened 2024-05-29 08:23 UTC by TheUnderScorer

2024-05-30 21:33 UTC, Orkuncakilkaya approved these changes

2024-06-03 06:18 UTC, JuroUhlar commented on readme.md
> +      // You can also access raw response
```suggestion
      // You can also access the raw response
```

2024-06-03 07:50 UTC, JuroUhlar commented on src/serverApiClient.ts
> +          error: err,
The `getEvent` handler above contains the following error transformation. Why is it used there and not here? 

`const error = (err as unknown) instanceof Error ? (err as Error).toString() : JSON.stringify(err)`

2024-06-03 08:02 UTC, JuroUhlar commented on contributing.md
>     node index.js
```suggestion
   node index.mjs
```

2024-06-03 08:34 UTC, JuroUhlar commented on src/serverApiClient.ts
> +          throw { ...(jsonResponse as EventError), response, status: response.status } as EventError
Just curious, why do we need `as EventError` twice here?

2024-06-03 08:38 UTC, TheUnderScorer commented on readme.md
> +---
Done!

2024-06-03 08:39 UTC, TheUnderScorer commented on src/serverApiClient.ts
> +          error: err,
No idea, but this transformation seems unnecessary complex. I've decided to remove it, the tests pass without it any way (expect for one snapshot)

2024-06-03 08:39 UTC, TheUnderScorer commented on src/serverApiClient.ts
> +          throw { ...(jsonResponse as EventError), response, status: response.status } as EventError
Good catch, it's not needed, fixed!

2024-06-03 11:16 UTC, JuroUhlar commented on readme.md
> +        console.log(err.response);
This example does not work, can you double-check all code snippets in the readme and update them if necessary? 

![image](https://github.com/fingerprintjs/fingerprintjs-pro-server-api-node-sdk/assets/11249993/b285cc6c-0e28-4af1-9959-774bdbc335f7)

2024-06-03 11:18 UTC, JuroUhlar commented on src/types.ts
>  export function isVisitorsError(response: any): response is EventError {
Why `is EventError` ? Shouldn't it be `is VisitorsError`?

2024-06-03 11:21 UTC, JuroUhlar commented on readme.md
> +        console.log(err.response);
Also shouldn't the example in the API reference section also be using these type guards instead of operating over `any` err objects?

2024-06-03 11:22 UTC, TheUnderScorer commented on src/types.ts
>  export function isVisitorsError(response: any): response is EventError {
Yep, good catch!

2024-06-03 11:22 UTC, TheUnderScorer commented on readme.md
> +        console.log(err.response);
Good catch! It was caused by the issue below

2024-06-03 11:27 UTC, JuroUhlar commented on readme.md
>        if (err.code === 429) {
Still broken, this should fix it

```suggestion
      if (err.status === 429) {
```

2024-06-03 11:29 UTC, JuroUhlar commented on readme.md
>        console.log(`error ${err.code}: `, err.error.message);
```suggestion
      console.log(`error ${err.status}: `, err.error?.message)
```

2024-06-03 11:35 UTC, JuroUhlar commented on readme.md
> +        console.log(err.response);
The code is still accessing properties incorrectly. Can you update snippets in the API reference as well? 

![image](https://github.com/fingerprintjs/fingerprintjs-pro-server-api-node-sdk/assets/11249993/fd0c2e0f-4a11-4f25-9603-33d93ea43c87)

2024-06-03 11:47 UTC, TheUnderScorer commented on readme.md
> +        console.log(err.response);
Fixed, thanks!

2024-06-03 16:20 UTC, JuroUhlar commented on readme.md
> +        console.log(err.response);
You were still missing some `.?` undefined checks and some examples were not using the type guards, here is what I had in mind: 
https://github.com/fingerprintjs/fingerprintjs-pro-server-api-node-sdk/pull/104/commits/c9523250ceb3ff5d8514648d455f9e2bdfd446c7

2024-06-04 08:44 UTC, JuroUhlar commented on readme.md
> +        console.log(err.response);
Some of the code snippets were still incorrect and not using the type guards. When reviewing snippets, its helpful to try running them. I made the following fixes, take a look pls :) Thanks!

https://github.com/fingerprintjs/fingerprintjs-pro-server-api-node-sdk/pull/104/commits/c9523250ceb3ff5d8514648d455f9e2bdfd446c7

2024-06-10 09:40 UTC, TheUnderScorer commented on readme.md
> +        console.log(err.response);
Thanks a lot for this @JuroUhlar!

2024-06-10 10:00 UTC, TheUnderScorer commented on src/webhook.ts
> +export function checkWebhookHeader(header: string, data: Buffer, secret: string): boolean {
Good point, done!

2024-06-10 10:01 UTC, TheUnderScorer commented on readme.md
> +import { checkWebhookHeader } from '@fingerprintjs/fingerprintjs-pro-server-api';
Done, thanks!

2024-06-11 13:27 UTC, JuroUhlar requested changes

2024-06-12 08:12 UTC, TheUnderScorer commented on src/webhook.ts
> +function checkWebhookSignature(signature: string, data: Buffer, secret: string) {
Makes sense, done! Sorry for the confusion

2024-06-12 08:13 UTC, TheUnderScorer commented on src/webhook.ts
> +      if (checkWebhookSignature(hash, data, secret)) {
Yep, good catch, thanks!

2024-06-12 08:14 UTC, TheUnderScorer commented on readme.md
> +To learn more, see the example in [example/sealedResults.mjs](./example/sealedResults.mjs) or the [API Reference](#sealed-results-api-reference).
Yep, it's not deployed yet. It will once we merge this PR.

2024-06-12 08:16 UTC, TheUnderScorer commented on example/deleteVisitor.mjs
> +  const client = new FingerprintJsServerApiClient({ region, apiKey: apiKey })
Since it's just a normal JavaScript file, there is no way to properly cast `region` to `Region` enum 😔

2024-06-12 08:17 UTC, TheUnderScorer commented on example/deleteVisitor.mjs
> +  const client = new FingerprintJsServerApiClient({ region, apiKey: apiKey })
But, I think we can improve it at least by little by making the `options.region` optional, since it works like this in other SDKs.

2024-06-12 08:25 UTC, TheUnderScorer commented on readme.md
> +See the full [API reference](https://fingerprintjs.github.io/fingerprintjs-pro-node-sdk/).
Done! We'll only need to check after the merge to make sure that these links point to correct functions in the API reference

2024-06-12 08:26 UTC, TheUnderScorer commented on example/sealedResults.mjs
Overall I like this idea, but it will introduce a minor, but still a breaking change, meaning that we will have to do a major release. I would prefer to avoid this for now, but we can do it if you insist.

2024-06-12 08:41 UTC, JuroUhlar commented on package.json
> +    "docs": "typedoc src/index.ts --out docs"
Maybe just a weird bug in my pnpm, using `npm run docs` works as expected

2024-06-12 09:57 UTC, JuroUhlar commented on example/sealedResults.mjs
Okay, let's do that in a separate task and PR. Enums in Typescript are just silly, I think we should [never use them](https://www.youtube.com/watch?v=jjMbPt_H3RQ).  

https://fingerprintjs.atlassian.net/browse/INTER-721

2024-06-12 14:11 UTC, JuroUhlar commented on example/deleteVisitor.mjs
> +  const client = new FingerprintJsServerApiClient({ region, apiKey: apiKey })
yeah, you need to do this every time

```ts
let region = Region.Global
if (envRegion === 'eu') {
  region = Region.EU
} else if (envRegion === 'ap') {
  region = Region.AP
}
```

+ 1 for getting rid of enums

2024-06-13 08:38 UTC, JuroUhlar approved these changes
Nice job!

2024-06-13 10:03 UTC, makma approved these changes

2024-06-13 10:15 UTC, makma commented on src/serverApiClient.ts
> +          status: 0,
Discussed via slack

2024-06-13 11:32 UTC, merged