docs: Add CODEOWNERS and contributing guide
fingerprintjs/fingerprintjs-pro-server-api-node-sdk pull request #14
Opened 2022-04-08 11:00 UTC by TheUnderScorer

2022-04-08 13:20 UTC, ilfa commented on contributing.md
> +Change version in package.json to x.y.z and push a commit with the message Release x.y.z, the npm-publish action will create a new tag vx.y.z and publish the package to the npm registry.
Check [GitHub action](https://github.com/fingerprintjs/fingerprintjs-pro-server-api-node-sdk/blob/main/.github/workflows/npm-publish.yml
) please.

It triggers only by `^Release (\\S+)` pattern. We should say about it here. Or we can use `generate-changelog` package as [in some other repositories](https://github.com/fingerprintjs/fingerprintjs-pro-spa/blob/main/package.json#L26).

2022-04-11 08:11 UTC, TheUnderScorer commented on contributing.md
> +Change version in package.json to x.y.z and push a commit with the message Release x.y.z, the npm-publish action will create a new tag vx.y.z and publish the package to the npm registry.
Good point, I've done some further changes to use `generate-changelog` like in other repositories!

2022-04-11 10:10 UTC, ilfa requested changes

2022-04-11 10:10 UTC, ilfa commented on package.json
> +    "release:major": "changelog -M && git add CHANGELOG.md && yarn version --major",
As `npm-publish-action` creates tag we don't need it to create it in this step. Please add [--no-git-tag-version](https://classic.yarnpkg.com/en/docs/cli/version#toc-yarn-version-no-git-tag-version) for `yarn version` call.

2022-04-11 10:10 UTC, ilfa commented on CHANGELOG.md
> +##### Chores
Al the list looks like mostly a spoiler for the next version =)

2022-04-11 10:20 UTC, TheUnderScorer commented on package.json
> +    "release:major": "changelog -M && git add CHANGELOG.md && yarn version --major",
Done!

2022-04-11 13:18 UTC, ilfa requested changes

2022-04-11 13:18 UTC, ilfa commented on package.json
> +    "generate-changelog": "^1.8.0",
Please move it to `devDependencies`

2022-04-11 13:21 UTC, TheUnderScorer commented on package.json
> +    "generate-changelog": "^1.8.0",
Done! :)

2022-04-11 13:26 UTC, ilfa approved these changes

2022-04-11 13:29 UTC, merged