refactor: switch to pnpm
fingerprintjs/fingerprintjs-pro-server-api-node-sdk pull request #93
Opened 2024-03-19 20:46 UTC by Orkuncakilkaya

2024-03-22 12:36 UTC, ilfa requested changes

2024-03-22 12:36 UTC, ilfa commented on package.json
> +    "@semantic-release/github": "^10.0.2",
semantic-release packages are redundant in this repo now, you can remove all of them

2024-03-22 12:36 UTC, ilfa commented on package.json
> +    "@types/node-fetch": "^2.6.11",
No need anymore

2024-03-22 12:36 UTC, ilfa commented on package.json
> +    "eslint": "^8.57.0",
You could remove eslint packages as the are dependencies of `@fingerprintjs/eslint-config-dx-team`
Also you could check deps of other reusable configs.

2024-03-22 12:36 UTC, ilfa commented on src/serverApiClient.ts
> +      .catch((err: any) => {
is it possible to use a wider type?

2024-03-22 12:36 UTC, ilfa commented on tsconfig.json
> +    "skipLibCheck": true,
What was the reason to change this rule?

2024-03-25 09:11 UTC, Orkuncakilkaya commented on tsconfig.json
> +    "skipLibCheck": true,
It was a leftover probably when I was try to run jest for this repository, will remove 👍

2024-03-25 09:19 UTC, Orkuncakilkaya commented on package.json
> +    "@types/node-fetch": "^2.6.11",
We need @types/node because we use these lines on sealedResults.ts file and it's a type dependency
```
import { createDecipheriv } from 'crypto'
import { inflateRaw } from 'zlib'
import { promisify } from 'util'
```

2024-03-25 10:43 UTC, ilfa commented on package.json
> +    "@types/node-fetch": "^2.6.11",
I mean `"@types/node-fetch": "^2.6.11",`

2024-03-25 19:12 UTC, Orkuncakilkaya commented on package.json
> +    "@types/node-fetch": "^2.6.11",
I see sorry I saw multiple lines starting with semantic-release and thought it was for all. Removed 👍

2024-03-26 11:30 UTC, Orkuncakilkaya commented on src/serverApiClient.ts
> +      .catch((err: any) => {
Github doesn't show this correctly but this is updated
<img width="867" alt="image" src="https://github.com/fingerprintjs/fingerprintjs-pro-server-api-node-sdk/assets/5910168/da7caa86-aa08-4e93-91fd-e3cc32801bb6">

2024-03-26 14:09 UTC, closed without merging